//
//  MovieData.swift
//  Veerabathini_Movies
//
//  Created by student on 4/24/22.
//

import Foundation
import UIKit

struct Movie{
    var title : String
    var image : UIImage
    var releasedYear : String
    var movieRating : String
    var boxOffice : String
    var moviePlot : String
    var cast :[String] = []
}

struct Genre{
    var category : String
    var movies : [Movie] = []
}

let genre1 = Genre(category: "Thriller", movies: [Movie(title: "The Guilty", image: UIImage(named: "The Guilty")!, releasedYear: "2021", movieRating: "6.3", boxOffice: "50M", moviePlot: "A troubled police detective demoted to 911 operator duty scrambles to save a distressed caller during a harrowing day of revelations -- and reckonings.", cast: ["Jake Gyllenhaal","Riley Keough","Peter Sarsgaard"]), Movie(title: "No Exit", image : UIImage(named: "No Exit")!, releasedYear: "2022", movieRating: "6.1", boxOffice: "20M", moviePlot: "A college student, on her way home from visiting her mother, gets stuck with a group of people at a mountain rest stop during a blizzard. Things take a turn for the worse when the young woman discovers a kidnapped child in a car belonging to one of the people inside, putting the group in a terrifying life-or-death situation as they struggle to escape while trying to discover who among them is the kidnapper.", cast: ["Havana Rose Liu","Danny Ramirez","David Rysdahl"]), Movie(title: "The Night House", image: UIImage(named: "The Night House")!, releasedYear: "2020", movieRating: "6.5", boxOffice: "15.5M", moviePlot: "Reeling from the unexpected death of her husband, Beth (Rebecca Hall) is left alone in the lakeside home he built for her. She tries as best she can to keep together-but then the dreams come. Disturbing visions of a presence in the house call to her, beckoning with a ghostly allure. But the harsh light of day washes away any proof of a haunting. Against the advice of her friends, she begins digging into his belongings, yearning for answers.", cast: ["Rebecca Hall","Sarah Goldberg","Vondie Curtis-Hall"]), Movie(title: "The Weekend Away", image: UIImage(named: "The Weekend Away")!, releasedYear: "2022", movieRating: "5.6", boxOffice: "50M", moviePlot: "When her best friend vanishes during a girls trip to Croatia, a woman races to figure out what happened. However, each clue yields another unsettling deception.", cast: ["Leighton Meester","Christina Wolfe","Ziad Bakri"]), Movie(title: "Old", image: UIImage(named: "Old")!, releasedYear: "2021", movieRating: "5.8", boxOffice: "90.1M", moviePlot: "A thriller about a family on a tropical holiday who discover that the secluded beach where they are relaxing for a few hours is somehow causing them to age rapidly reducing their entire lives into a single day.", cast: ["Gael Garcia Bernal","Vicky Krieps","Rufus Sewell"])])

let genre2 = Genre(category: "Horror", movies: [Movie(title: "X", image: UIImage(named: "X")!, releasedYear: "2022", movieRating: "6.8", boxOffice: "12.9M", moviePlot: "A group of actors sets out to make an adult film in rural Texas under the noses of their reclusive hosts, but when the elderly couple catches their young guests in the act, the cast finds themselves in a desperate fight for their lives.", cast: ["Mia Goth","Jenna Ortega","Brittany Snow"]), Movie(title: "Ready or Not", image: UIImage(named: "Ready or Not")!, releasedYear: "2019", movieRating: "6.8", boxOffice: "57.6M", moviePlot: "Grace couldn't be happier after she marries the man of her dreams at his family's luxurious estate. There's just one catch -- she must now hide from midnight until dawn while her new in-laws hunt her down with guns, crossbows and other weapons. As Grace desperately tries to survive the night, she soon finds a way to turn the tables on her not-so-lovable relatives.", cast: ["Samara Weaving","Adam Brody","Mark O'Brien"]), Movie(title: "Escape Room", image: UIImage(named: "Escape Room")!, releasedYear: "2019", movieRating: "9.1", boxOffice: "155.7M", moviePlot: "Six adventurous strangers travel to a mysterious building to experience the escape room -- a game where players compete to solve a series of puzzles to win $10,000. What starts out as seemingly innocent fun soon turns into a living nightmare as the four men and two women discover each room is an elaborate trap that's part of a sadistic game of life or death.", cast: ["James A. Janisse"]), Movie(title: "The Nun", image: UIImage(named: "The Nun")!, releasedYear: "2018", movieRating: "5.3", boxOffice: "365.6M", moviePlot: "When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together, they uncover the order's unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of a demonic nun.", cast: ["Demian Bichir","Taissa Farmiga","Jonas Bloquet"]), Movie(title: "The Invisible Man", image: UIImage(named: "The Invisible Man")!, releasedYear: "2020", movieRating: "7.1", boxOffice: "143.2M", moviePlot: "After staging his own suicide, a crazed scientist uses his power to become invisible to stalk and terrorize his ex-girlfriend. When the police refuse to believe her story, she decides to take matters into her own hands and fight back.", cast: ["Elisabeth Moss","Oliver Jackson-Cohen","Harriet Dyer"])])

let genre3 = Genre(category: "Comedy", movies: [Movie(title: "Dog", image: UIImage(named: "Dog")!, releasedYear: "2022", movieRating: "6.5", boxOffice: "73.4M", moviePlot: "With a dog named Lulu by his side, Army Ranger Briggs races down the Pacific Coast to make it to a soldier's funeral on time. Along the way, Briggs and Lulu drive each other completely crazy, break a handful of laws, narrowly evade death, and learn to let down their guards to have a fighting chance of finding happiness.", cast: ["Channing Tatum","Ryder McLaughlin", "Aavi Haas"]), Movie(title: "Red Notice", image: UIImage(named: "Red Notice")!, releasedYear: "2021", movieRating: "6.3", boxOffice: "2M", moviePlot: "In the world of international crime, an Interpol agent attempts to hunt down and capture the world's most wanted art thief.", cast: ["Dwayne Johnson","Ryan Reynolds","Gal Gadot"]), Movie(title: "Don't Look Up", image: UIImage(named: "Dont Look Up")!, releasedYear: "2021", movieRating: "5.5", boxOffice: "1M", moviePlot: "Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.", cast: ["Leonardo DiCaprio","Jennifer Lawrence","Rob Morgan"]), Movie(title: "The Gentlemen", image: UIImage(named: "The Gentlemen")!, releasedYear: "2019", movieRating: "7.8", boxOffice: "30M", moviePlot: "Mickey Pearson is an American expatriate who became rich by building a highly profitable marijuana empire in London. When word gets out that he's looking to cash out of the business, it soon triggers an array of plots and schemes -- including bribery and blackmail -- from shady characters who want to steal his domain.", cast: ["Matthew McConaughey","Charlie Hunnam","Michelle Dockery"]), Movie(title: "Marry Me", image: UIImage(named: "Marry Me")!, releasedYear: "2022", movieRating: "6.1", boxOffice: "49M", moviePlot: "Pop superstar Kat Valdez is about to get married before an audience of her loyal fans. However, seconds before the ceremony, she learns about her fiance's cheating ways and has a meltdown on stage. In a moment of inspired insanity, Kat locks eyes with a total stranger in the crowd and marries him on the spot. As forces conspire to separate the unlikely newlyweds, they must soon decide if two people from such different worlds can find true love together.", cast: ["Jennifer Lopez","Owen Wilson","Maluma"])])

let genres = [genre1, genre2, genre3]
