//
//  GrocerySection.swift
//  Veerabathini_GroceryApp
//
//  Created by student on 4/12/22.
//

import Foundation

struct GrocerySections{
    var section = ""
    var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let grocerySection1 = GrocerySections(section: "Pasta", items_Array: [GroceryItem(itemName: "Angel Hair Pasta", itemImage: "angel hair pasta", itemInfo: "The long, delicate strands of angel hair pasta (aka capellini) are best served in light or creamy sauces. The thin strands can go M.I.A. in chunky, meaty sauces."), GroceryItem(itemName: "Bow Tie Pasta", itemImage: "bow tie pasta", itemInfo: "Use bow tie pasta to dress up any dish that calls for small pasta shapes, such as penne or shells. Also known as farfalle."), GroceryItem(itemName: "Bucatini Pasta", itemImage: "bucatini pasta", itemInfo: "These long, hollow spaghetti-like tubes (aka perciatelli) are unusual and fun! Try them in casseroles or Asian stir-fries, or tossed with a fresh tomato sauce."), GroceryItem(itemName: "Ditalini Pasta", itemImage: "ditalini pasta", itemInfo: "Medium-sized, very short tubes with smooth sides. Like most short pasta shapes, ditali are excellent used in soups, pasta salads, and to stand up to chunky sauces."), GroceryItem(itemName: "Fettuccine Pasta", itemImage: "fettuccine pasta", itemInfo: "Fettuccine is an egg pasta cut into long, narrow ribbons. It is often served with cream sauces, as in the classic Fettuccine Alfredo. You can use fettuccine in any recipe that calls for linguine or spaghetti.")])

let grocerySection2 = GrocerySections(section: "Cheese", items_Array: [GroceryItem(itemName: "Gouda", itemImage: "gouda cheese", itemInfo: "Gouda, or How-da as the locals say, is a Dutch cheese named after the city of Gouda in the Netherlands. If truth be told, it is one of the most popular cheeses in the world, accounting for 50 to 60% of the world's cheese consumption. It is a semi-hard cheese celebrated for its rich, unique flavour and smooth texture. The original cheese markets in Gouda is one of the last standing commercial cheese markets in the Netherlands. Since the name is not protected, it has become a generic classification for all cheeses produced and sold under the name Gouda."), GroceryItem(itemName: "American Cheese", itemImage: "american cheese", itemInfo: "American cheese is processed cheese made from a blend of milk, milk fats and solids, other fats and whey protein concentrate. At first, it was made from a mixture of cheeses, more often than not Colby and Cheddar. Since blended cheeses are no longer used, it cannot be legally called “cheese” and has to be labelled as “processed cheese”, “cheese product“, etc. Sometimes, it is called American slices or American singles instead of the word cheese. Under the U.S. Code of Federal Regulations, American cheese is a type of pasteurised processed cheese."), GroceryItem(itemName: "Cheddar", itemImage: "cheddar cheese", itemInfo: "Cheddar cheese, the most widely purchased and eaten cheese in the world is always made from cow's milk. It is a hard and natural cheese that has a slightly crumbly texture if properly cured and if it is too young, the texture is smooth. It gets a sharper taste as it matures, over a period of time between 9 to 24 months. Shaped like a drum, 15 inches in diameter, Cheddar cheese is natural rind bound in cloth while its colour generally ranges from white to pale yellow. However, some Cheddars may have a manually added yellow-orange colour."), GroceryItem(itemName: "Parmesan", itemImage: "parmesan cheese", itemInfo: "The Parmigiano Reggiano or Parmesan cheese as it is called in English is considered to be among the top cheeses by cheese connoisseurs. Today, it is produced by various producers. However, PDO designation states that for a cheese to be called as Parmesan, it has to be produced from cows grazing on fresh grass and hay."), GroceryItem(itemName: "Mozzarella", itemImage: "mozzarella cheese", itemInfo: "Mozzarella cheese is a sliceable curd cheese originating in Italy. Traditional Mozzarella cheese is made from milk of water buffalos herded in very few countries such as Italy and Bulgaria. As a result, most of the Mozzarella cheeses available now are made from cow's milk.")])

let grocerySection3 = GrocerySections(section: "Baked Food", items_Array: [GroceryItem(itemName: "Biscuit", itemImage: "biscuit", itemInfo: "A term used for a variety of baked, commonly flour-based food products.[2] The term is applied to two distinct products in North America and the United Kingdom,[3] and is also distinguished from U.S. versions in the Commonwealth of Nations and Europe."), GroceryItem(itemName: "Bread", itemImage: "bread", itemInfo: "A staple food prepared from a dough of flour and water, usually by baking."), GroceryItem(itemName: "Brownie", itemImage: "brownie", itemInfo: "A flat, baked dessert square that was developed in the United States at the end of the 19th century[7] and popularized in both the U.S. and Canada during the first half of the 20th century"), GroceryItem(itemName: "Cake", itemImage: "cake", itemInfo: "A form of sweet dessert that is typically baked. In its oldest forms, cakes were modifications of breads but now cover a wide range of preparations that can be simple or elaborate."), GroceryItem(itemName: "Pastry", itemImage: "pastry", itemInfo: "A dough of flour and water and shortening that may be savoury or sweetened. Sweetened pastries are often described as bakers' confectionery.")])

let grocerySection4 = GrocerySections(section: "Meat", items_Array: [GroceryItem(itemName: "Pork", itemImage: "pork", itemInfo: "High in vitamin B1 as well as omega-6 fatty acids, pork is one of the world’s most popular types of meat. From Italian sausage to barbecued pork ribs to bacon, pork is easy to prepare and incredibly flavorful. For an easy weeknight dinner, quick brine pork chops before you sear them off in a cast-iron skillet. Serve with apple mostarda and grits."), GroceryItem(itemName: "Beef", itemImage: "beef", itemInfo: "From a prehistoric looking T-bone steak to your average ballpark hot dogs and beef jerky, beef is a delicacy best enjoyed sparingly. It shares a main fatty acid with none other than olive oil—oleic acid. Ground beef makes for quick and easy burgers: combine the meat with egg, onions, salt, and spices or flavorings of your choice (think Worcestershire sauce and powdered garlic) and form the mixture into patties. Grill for a few minutes on either side and pair with your favorite burger toppings."), GroceryItem(itemName: "Lamb", itemImage: "lamb", itemInfo: "Lamb is categorized as meat from a young sheep under a year old. While lamb tends to be on the more expensive side of the different meats, it’s also thought to be one of the healthiest, with good levels of nutrients. Sear a rack of lamb in a cast-iron skillet before basting in garlic butter and finishing in a 375°F oven for 5 minutes."), GroceryItem(itemName: "Goat", itemImage: "goat", itemInfo: "A slightly tough muscular composition makes goat a popular addition to stews and braises, where a low and slow cooking technique can best break down the fats and infuse the meat with flavor."), GroceryItem(itemName: "Chicken", itemImage: "chicken", itemInfo: "Chicken meat is high and protein and low in fat, which varies in white and dark meat. Boneless, skinless chicken breast meat is one of the only types of meat that doesn't contain saturated fat. A roasted chicken is one of life’s simplest pleasures. Brush the chicken with clarified butter and season all sides with salt, then roast at 475°F for 20–25 minutes. Reduce heat to 400°F and continue to roast another 30-45 minutes, until thighs and center of the chicken breast registers 160°F and the juices run clear. Let rest at least 20 minutes before carving.")])

let grocerySection5 = GrocerySections(section: "Cereals", items_Array: [GroceryItem(itemName: "Rice", itemImage: "rice", itemInfo: "Rice is a staple food in different parts of the world and has to top our cereal food list. People consume rice because it’s healthy and very filling and an ideal gluten-free meal option."), GroceryItem(itemName: "Maize", itemImage: "maize", itemInfo: "Corn is a very popular cereal among Americans and one of the major on cereals list , but it’s also used in many parts of the world. It is one of the oldest types of cereals known to humankind and is a very healthy breakfast option in the form of corn flakes."), GroceryItem(itemName: "Oats", itemImage: "oats", itemInfo: "One of the common in cereals name list is oats or oatmeal, which are mainly consumed as porridge. It comes in various forms and can be eaten in a lot of ways. Oats is a very trendy breakfast these days. There are different flavors and oats price that you can choose according to your taste end pocket!"), GroceryItem(itemName: "Rye", itemImage: "rye", itemInfo: "Rye is typically grown in cold climatic conditions and is chiefly used for the production of alcoholic drinks. It is also used for making food for animals and certain types of flour."), GroceryItem(itemName: "Barley", itemImage: "barley", itemInfo: "Barley is grown in temperate climates across the world. It is observed that barley can grow in conditions where wheat can’t grow. Barley is one of the most important types of cereals in India after rice and wheat.")])

let grocerySections = [grocerySection1, grocerySection2, grocerySection3, grocerySection4, grocerySection5]
